function f(a){throw a;}var h=void 0,j=true,k=null,n=false;function p(a){return function(b){this[a]=b}}function aa(a){return function(){return this[a]}}var q,ba=ba||{},s=this;function ca(a){for(var a=a.split("."),b=s,c;c=a.shift();)if(b[c]!=k)b=b[c];else return k;return b}function t(){}
function da(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function u(a){return da(a)=="array"}function ea(a){var b=da(a);return b=="array"||b=="object"&&typeof a.length=="number"}function v(a){return typeof a=="string"}function fa(a){return da(a)=="function"}function ga(a){a=da(a);return a=="object"||a=="array"||a=="function"}function w(a){return a[ha]||(a[ha]=++ia)}var ha="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ia=0;
function ja(a,b,c){return a.call.apply(a.bind,arguments)}function ka(a,b,c){a||f(Error());if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}function y(a,b,c){y=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ja:ka;return y.apply(k,arguments)}var z=Date.now||function(){return+new Date};
function A(a,b){function c(){}c.prototype=b.prototype;a.$=b.prototype;a.prototype=new c};function la(a){this.stack=Error().stack||"";if(a)this.message=String(a)}A(la,Error);la.prototype.name="CustomError";function ma(a,b){for(var c=1;c<arguments.length;c++)var d=String(arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,d);return a}var na=/^[a-zA-Z0-9\-_.!~*'()]*$/;function oa(a){a=String(a);return!na.test(a)?encodeURIComponent(a):a}function pa(a){if(!qa.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(ra,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(sa,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(ta,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(ua,"&quot;"));return a}
var ra=/&/g,sa=/</g,ta=/>/g,ua=/\"/g,qa=/[&<>\"]/;
function va(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),g=Math.max(d.length,e.length),i=0;c==0&&i<g;i++){var l=d[i]||"",m=e[i]||"",o=RegExp("(\\d*)(\\D*)","g"),x=RegExp("(\\d*)(\\D*)","g");do{var r=o.exec(l)||["","",""],E=x.exec(m)||["","",""];if(r[0].length==0&&E[0].length==0)break;c=wa(r[1].length==0?0:parseInt(r[1],10),E[1].length==0?0:parseInt(E[1],10))||wa(r[2].length==0,E[2].length==0)||wa(r[2],E[2])}while(c==
0)}return c}function wa(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};function xa(a,b){b.unshift(a);la.call(this,ma.apply(k,b));b.shift();this.Lc=a}A(xa,la);xa.prototype.name="AssertionError";function ya(a,b){f(new xa("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};var B=Array.prototype,za=B.indexOf?function(a,b,c){return B.indexOf.call(a,b,c)}:function(a,b,c){c=c==k?0:c<0?Math.max(0,a.length+c):c;if(v(a))return!v(b)||b.length!=1?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Aa=B.forEach?function(a,b,c){B.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=v(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};function Ba(a){return B.concat.apply(B,arguments)}
function Ca(a){if(u(a))return Ba(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}}function Da(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if(u(d)||(e=ea(d))&&d.hasOwnProperty("callee"))a.push.apply(a,d);else if(e)for(var g=a.length,i=d.length,l=0;l<i;l++)a[g+l]=d[l];else a.push(d)}};function Ea(a){var b=C,c;for(c in b)a.call(h,b[c],c,b)}function Fa(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Ga(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}var Ha="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function Ia(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<Ha.length;g++)c=Ha[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Ja(a){if(typeof a.ea=="function")return a.ea();if(v(a))return a.split("");if(ea(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Fa(a)}function Ka(a,b,c){if(typeof a.forEach=="function")a.forEach(b,c);else if(ea(a)||v(a))Aa(a,b,c);else{var d;if(typeof a.na=="function")d=a.na();else if(typeof a.ea!="function")if(ea(a)||v(a)){d=[];for(var e=a.length,g=0;g<e;g++)d.push(g)}else d=Ga(a);else d=h;for(var e=Ja(a),g=e.length,i=0;i<g;i++)b.call(c,e[i],d&&d[i],a)}};function La(a,b){this.Q={};this.k=[];var c=arguments.length;if(c>1){c%2&&f(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof La?(c=a.na(),d=a.ea()):(c=Ga(a),d=Fa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}}q=La.prototype;q.e=0;q.jc=0;q.ea=function(){Ma(this);for(var a=[],b=0;b<this.k.length;b++)a.push(this.Q[this.k[b]]);return a};q.na=function(){Ma(this);return this.k.concat()};q.K=function(a){return Na(this.Q,a)};
q.remove=function(a){return Na(this.Q,a)?(delete this.Q[a],this.e--,this.jc++,this.k.length>2*this.e&&Ma(this),j):n};function Ma(a){if(a.e!=a.k.length){for(var b=0,c=0;b<a.k.length;){var d=a.k[b];Na(a.Q,d)&&(a.k[c++]=d);b++}a.k.length=c}if(a.e!=a.k.length){for(var e={},c=b=0;b<a.k.length;)d=a.k[b],Na(e,d)||(a.k[c++]=d,e[d]=1),b++;a.k.length=c}}q.get=function(a,b){return Na(this.Q,a)?this.Q[a]:b};q.set=function(a,b){Na(this.Q,a)||(this.e++,this.k.push(a),this.jc++);this.Q[a]=b};q.n=function(){return new La(this)};
function Na(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Oa=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Pa(a,b){var c;a instanceof Pa?(this.sa(b==k?a.H:b),Qa(this,a.S),Ra(this,a.La),Sa(this,a.M),Ta(this,a.ga),Ua(this,a.q),Va(this,a.B.n()),Wa(this,a.za)):a&&(c=String(a).match(Oa))?(this.sa(!!b),Qa(this,c[1]||"",j),Ra(this,c[2]||"",j),Sa(this,c[3]||"",j),Ta(this,c[4]),Ua(this,c[5]||"",j),Va(this,c[6]||"",j),Wa(this,c[7]||"",j)):(this.sa(!!b),this.B=new Xa(k,this,this.H))}q=Pa.prototype;q.S="";q.La="";q.M="";q.ga=k;q.q="";q.za="";q.sc=n;q.H=n;
q.toString=function(){if(this.z)return this.z;var a=[];this.S&&a.push(Ya(this.S,Za),":");this.M&&(a.push("//"),this.La&&a.push(Ya(this.La,Za),"@"),a.push(v(this.M)?encodeURIComponent(this.M):k),this.ga!=k&&a.push(":",String(this.ga)));this.q&&(this.M&&this.q.charAt(0)!="/"&&a.push("/"),a.push(Ya(this.q,this.q.charAt(0)=="/"?$a:ab)));var b=String(this.B);b&&a.push("?",b);this.za&&a.push("#",Ya(this.za,bb));return this.z=a.join("")};
q.n=function(){return cb(this.S,this.La,this.M,this.ga,this.q,this.B.n(),this.za,this.H)};function Qa(a,b,c){D(a);delete a.z;a.S=c?b?decodeURIComponent(b):"":b;if(a.S)a.S=a.S.replace(/:$/,"")}function Ra(a,b,c){D(a);delete a.z;a.La=c?b?decodeURIComponent(b):"":b}function Sa(a,b,c){D(a);delete a.z;a.M=c?b?decodeURIComponent(b):"":b}function Ta(a,b){D(a);delete a.z;b?(b=Number(b),(isNaN(b)||b<0)&&f(Error("Bad port number "+b)),a.ga=b):a.ga=k}
function Ua(a,b,c){D(a);delete a.z;a.q=c?b?decodeURIComponent(b):"":b}function Va(a,b,c){D(a);delete a.z;b instanceof Xa?(a.B=b,a.B.vb=a,a.B.sa(a.H)):(c||(b=Ya(b,db)),a.B=new Xa(b,a,a.H))}function G(a,b,c){D(a);delete a.z;a.B.set(b,c)}function eb(a,b,c){D(a);delete a.z;u(c)||(c=[String(c)]);a=a.B;H(a);fb(a);b=I(a,b);if(a.K(b)){var d=a.f.get(b);u(d)?a.e-=d.length:a.e--}c.length>0&&(a.f.set(b,c),a.e+=c.length)}function Wa(a,b,c){D(a);delete a.z;a.za=c?b?decodeURIComponent(b):"":b}
function J(a){D(a);G(a,"zx",Math.floor(Math.random()*2147483648).toString(36)+Math.abs(Math.floor(Math.random()*2147483648)^z()).toString(36));return a}function D(a){a.sc&&f(Error("Tried to modify a read-only Uri"))}q.sa=function(a){this.H=a;this.B&&this.B.sa(a);return this};function cb(a,b,c,d,e,g,i,l){l=new Pa(k,l);a&&Qa(l,a);b&&Ra(l,b);c&&Sa(l,c);d&&Ta(l,d);e&&Ua(l,e);g&&Va(l,g);i&&Wa(l,i);return l}var gb=/^[a-zA-Z0-9\-_.!~*'():\/;?]*$/;
function Ya(a,b){var c=k;v(a)&&(c=a,gb.test(c)||(c=encodeURI(a)),c.search(b)>=0&&(c=c.replace(b,hb)));return c}function hb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Za=/[#\/\?@]/g,ab=/[\#\?:]/g,$a=/[\#\?]/g,db=/[\#\?@]/g,bb=/#/g;function Xa(a,b,c){this.O=a||k;this.vb=b||k;this.H=!!c}
function H(a){if(!a.f&&(a.f=new La,a.e=0,a.O))for(var b=a.O.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=k,g=k;d>=0?(e=b[c].substring(0,d),g=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=I(a,e);a.add(e,g?decodeURIComponent(g.replace(/\+/g," ")):"")}}q=Xa.prototype;q.f=k;q.e=k;q.add=function(a,b){H(this);fb(this);a=I(this,a);if(this.K(a)){var c=this.f.get(a);u(c)?c.push(b):this.f.set(a,[c,b])}else this.f.set(a,b);this.e++;return this};
q.remove=function(a){H(this);a=I(this,a);if(this.f.K(a)){fb(this);var b=this.f.get(a);u(b)?this.e-=b.length:this.e--;return this.f.remove(a)}return n};q.K=function(a){H(this);a=I(this,a);return this.f.K(a)};q.na=function(){H(this);for(var a=this.f.ea(),b=this.f.na(),c=[],d=0;d<b.length;d++){var e=a[d];if(u(e))for(var g=0;g<e.length;g++)c.push(b[d]);else c.push(b[d])}return c};
q.ea=function(a){H(this);if(a)if(a=I(this,a),this.K(a)){var b=this.f.get(a);if(u(b))return b;else a=[],a.push(b)}else a=[];else for(var b=this.f.ea(),a=[],c=0;c<b.length;c++){var d=b[c];u(d)?Da(a,d):a.push(d)}return a};q.set=function(a,b){H(this);fb(this);a=I(this,a);if(this.K(a)){var c=this.f.get(a);u(c)?this.e-=c.length:this.e--}this.f.set(a,b);this.e++;return this};q.get=function(a,b){H(this);a=I(this,a);if(this.K(a)){var c=this.f.get(a);return u(c)?c[0]:c}else return b};
q.toString=function(){if(this.O)return this.O;if(!this.f)return"";for(var a=[],b=0,c=this.f.na(),d=0;d<c.length;d++){var e=c[d],g=oa(e),e=this.f.get(e);if(u(e))for(var i=0;i<e.length;i++)b>0&&a.push("&"),a.push(g),e[i]!==""&&a.push("=",oa(e[i])),b++;else b>0&&a.push("&"),a.push(g),e!==""&&a.push("=",oa(e)),b++}return this.O=a.join("")};function fb(a){delete a.mb;delete a.O;a.vb&&delete a.vb.z}q.n=function(){var a=new Xa;if(this.mb)a.mb=this.mb;if(this.O)a.O=this.O;if(this.f)a.f=this.f.n();return a};
function I(a,b){var c=String(b);a.H&&(c=c.toLowerCase());return c}q.sa=function(a){a&&!this.H&&(H(this),fb(this),Ka(this.f,function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.add(d,a))},this));this.H=a};function ib(a){return jb(a||arguments.callee.caller,[])}
function jb(a,b){var c=[];if(za(b,a)>=0)c.push("[...circular reference...]");else if(a&&b.length<50){c.push(kb(a)+"(");for(var d=a.arguments,e=0;e<d.length;e++){e>0&&c.push(", ");var g;g=d[e];switch(typeof g){case "object":g=g?"object":"null";break;case "string":break;case "number":g=String(g);break;case "boolean":g=g?"true":"false";break;case "function":g=(g=kb(g))?g:"[fn]";break;default:g=typeof g}g.length>40&&(g=g.substr(0,40)+"...");c.push(g)}b.push(a);c.push(")\n");try{c.push(jb(a.caller,b))}catch(i){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function kb(a){if(lb[a])return lb[a];a=String(a);if(!lb[a]){var b=/function ([^\(]+)/.exec(a);lb[a]=b?b[1]:"[Anonymous]"}return lb[a]}var lb={};function mb(a,b,c,d,e){this.reset(a,b,c,d,e)}mb.prototype.Fc=0;mb.prototype.Nb=k;mb.prototype.Mb=k;var nb=0;mb.prototype.reset=function(a,b,c,d,e){this.Fc=typeof e=="number"?e:nb++;this.Pc=d||z();this.Ea=a;this.uc=b;this.Kc=c;delete this.Nb;delete this.Mb};mb.prototype.hc=p("Ea");function K(a){this.vc=a}K.prototype.Xa=k;K.prototype.Ea=k;K.prototype.kb=k;K.prototype.Pb=k;function L(a,b){this.name=a;this.value=b}L.prototype.toString=aa("name");var ob=new L("SEVERE",1E3),pb=new L("WARNING",900),qb=new L("INFO",800),rb=new L("CONFIG",700),sb=new L("FINE",500),tb=new L("FINEST",300);q=K.prototype;q.getParent=aa("Xa");q.hc=p("Ea");function ub(a){if(a.Ea)return a.Ea;if(a.Xa)return ub(a.Xa);ya("Root logger has no level set.");return k}
q.log=function(a,b,c){if(a.value>=ub(this).value){a=this.rc(a,b,c);b="log:"+a.uc;s.console&&(s.console.timeStamp?s.console.timeStamp(b):s.console.markTimeline&&s.console.markTimeline(b));s.msWriteProfilerMark&&s.msWriteProfilerMark(b);for(b=this;b;){var c=b,d=a;if(c.Pb)for(var e=0,g=h;g=c.Pb[e];e++)g(d);b=b.getParent()}}};
q.rc=function(a,b,c){var d=new mb(a,String(b),this.vc);if(c){d.Nb=c;var e;var g=arguments.callee.caller;try{var i;var l=ca("window.location.href");if(v(c))i={message:c,name:"Unknown error",lineNumber:"Not available",fileName:l,stack:"Not available"};else{var m,o,x=n;try{m=c.lineNumber||c.Jc||"Not available"}catch(r){m="Not available",x=j}try{o=c.fileName||c.filename||c.sourceURL||l}catch(E){o="Not available",x=j}i=x||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:m,
fileName:o,stack:c.stack||"Not available"}:c}e="Message: "+pa(i.message)+'\nUrl: <a href="view-source:'+i.fileName+'" target="_new">'+i.fileName+"</a>\nLine: "+i.lineNumber+"\n\nBrowser stack:\n"+pa(i.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+pa(ib(g)+"-> ")}catch(F){e="Exception trying to expose exception! You win, we lose. "+F}d.Mb=e}return d};q.I=function(a,b){this.log(ob,a,b)};q.va=function(a,b){this.log(pb,a,b)};q.info=function(a,b){this.log(qb,a,b)};function M(a,b){a.log(sb,b,h)}
var vb={},wb=k;function xb(a){wb||(wb=new K(""),vb[""]=wb,wb.hc(rb));var b;if(!(b=vb[a])){b=new K(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=xb(a.substr(0,c));if(!c.kb)c.kb={};c.kb[d]=b;b.Xa=c;vb[a]=b}return b};function yb(){this.dc=z()}new yb;yb.prototype.set=p("dc");yb.prototype.reset=function(){this.set(z())};yb.prototype.get=aa("dc");function N(){}N.prototype.Jb=n;N.prototype.la=function(){if(!this.Jb)this.Jb=j,this.r()};N.prototype.r=function(){this.oc&&zb.apply(k,this.oc)};function zb(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ea(d)?zb.apply(k,d):d&&typeof d.la=="function"&&d.la()}};var Ab;function O(a,b){this.type=a;this.currentTarget=this.target=b}A(O,N);O.prototype.r=function(){delete this.type;delete this.target;delete this.currentTarget};O.prototype.pa=n;O.prototype.$a=j;var Bb,Cb,Db,Eb;function Fb(){return s.navigator?s.navigator.userAgent:k}Eb=Db=Cb=Bb=n;var Gb;if(Gb=Fb()){var Hb=s.navigator;Bb=Gb.indexOf("Opera")==0;Cb=!Bb&&Gb.indexOf("MSIE")!=-1;Db=!Bb&&Gb.indexOf("WebKit")!=-1;Eb=!Bb&&!Db&&Hb.product=="Gecko"}var Ib=Bb,P=Cb,Jb=Eb,Kb=Db,Lb=s.navigator,Mb=(Lb&&Lb.platform||"").indexOf("Mac")!=-1,Nb;
a:{var Ob="",Pb;if(Ib&&s.opera)var Qb=s.opera.version,Ob=typeof Qb=="function"?Qb():Qb;else if(Jb?Pb=/rv\:([^\);]+)(\)|;)/:P?Pb=/MSIE\s+([^\);]+)(\)|;)/:Kb&&(Pb=/WebKit\/(\S+)/),Pb)var Rb=Pb.exec(Fb()),Ob=Rb?Rb[1]:"";if(P){var Sb,Tb=s.document;Sb=Tb?Tb.documentMode:h;if(Sb>parseFloat(Ob)){Nb=String(Sb);break a}}Nb=Ob}var Ub={},Vb={};P&&(Vb[9]||(Vb[9]=P&&document.documentMode&&document.documentMode>=9));P&&(Ub["8"]||(Ub["8"]=va(Nb,"8")>=0));var Wb=new Function("a","return a");function Xb(a,b){a&&this.Ua(a,b)}A(Xb,O);q=Xb.prototype;q.target=k;q.relatedTarget=k;q.offsetX=0;q.offsetY=0;q.clientX=0;q.clientY=0;q.screenX=0;q.screenY=0;q.button=0;q.keyCode=0;q.charCode=0;q.ctrlKey=n;q.altKey=n;q.shiftKey=n;q.metaKey=n;q.Dc=n;q.Lb=k;
q.Ua=function(a,b){var c=this.type=a.type;O.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(Jb){var e;a:{try{Wb(d.nodeName);e=j;break a}catch(g){}e=n}e||(d=k)}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Dc=Mb?a.metaKey:a.ctrlKey;this.state=a.state;this.Lb=a;delete this.$a;delete this.pa};q.r=function(){Xb.$.r.call(this);this.relatedTarget=this.currentTarget=this.target=this.Lb=k};function Yb(){}var Zb=0;q=Yb.prototype;q.key=0;q.qa=n;q.Ab=n;q.Ua=function(a,b,c,d,e,g){fa(a)?this.Rb=j:a&&a.handleEvent&&fa(a.handleEvent)?this.Rb=n:f(Error("Invalid listener argument"));this.Fa=a;this.cc=b;this.src=c;this.type=d;this.capture=!!e;this.ob=g;this.Ab=n;this.key=++Zb;this.qa=n};q.handleEvent=function(a){return this.Rb?this.Fa.call(this.ob||this.src,a):this.Fa.handleEvent.call(this.Fa,a)};function Q(a,b){this.Vb=b;this.da=[];a>this.Vb&&f(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var c=0;c<a;c++)this.da.push(this.L?this.L():{})}A(Q,N);Q.prototype.L=k;Q.prototype.Ib=k;function $b(a){return a.da.length?a.da.pop():a.L?a.L():{}}function ac(a,b){a.da.length<a.Vb?a.da.push(b):bc(a,b)}function bc(a,b){if(a.Ib)a.Ib(b);else if(ga(b))if(fa(b.la))b.la();else for(var c in b)delete b[c]}
Q.prototype.r=function(){Q.$.r.call(this);for(var a=this.da;a.length;)bc(this,a.pop());delete this.da};var cc,dc=(cc="ScriptEngine"in s&&s.ScriptEngine()=="JScript")?s.ScriptEngineMajorVersion()+"."+s.ScriptEngineMinorVersion()+"."+s.ScriptEngineBuildVersion():"0";var ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc;
(function(){function a(){return{e:0,C:0}}function b(){return[]}function c(){function a(b){b=i.call(a.src,a.key,b);if(!b)return b}return a}function d(){return new Yb}function e(){return new Xb}var g=cc&&!(va(dc,"5.7")>=0),i;jc=function(a){i=a};if(g){ec=function(){return $b(l)};fc=function(a){ac(l,a)};gc=function(){return $b(m)};hc=function(a){ac(m,a)};ic=function(){return $b(o)};kc=function(){ac(o,c())};lc=function(){return $b(x)};mc=function(a){ac(x,a)};nc=function(){return $b(r)};oc=function(a){ac(r,
a)};var l=new Q(0,600);l.L=a;var m=new Q(0,600);m.L=b;var o=new Q(0,600);o.L=c;var x=new Q(0,600);x.L=d;var r=new Q(0,600);r.L=e}else ec=a,fc=t,gc=b,hc=t,ic=c,kc=t,lc=d,mc=t,nc=e,oc=t})();var pc={},R={},C={},qc={};
function rc(a,b,c,d,e){if(b)if(u(b)){for(var g=0;g<b.length;g++)rc(a,b[g],c,d,e);return k}else{var d=!!d,i=R;b in i||(i[b]=ec());i=i[b];d in i||(i[d]=ec(),i.e++);var i=i[d],l=w(a),m;i.C++;if(i[l]){m=i[l];for(g=0;g<m.length;g++)if(i=m[g],i.Fa==c&&i.ob==e){if(i.qa)break;return m[g].key}}else m=i[l]=gc(),i.e++;g=ic();g.src=a;i=lc();i.Ua(c,g,a,b,d,e);c=i.key;g.key=c;m.push(i);pc[c]=i;C[l]||(C[l]=gc());C[l].push(i);a.addEventListener?(a==s||!a.Fb)&&a.addEventListener(b,g,d):a.attachEvent(b in qc?qc[b]:
qc[b]="on"+b,g);return c}else f(Error("Invalid event type"))}function sc(a,b,c,d,e){if(u(b))for(var g=0;g<b.length;g++)sc(a,b[g],c,d,e);else{d=!!d;a:{g=R;if(b in g&&(g=g[b],d in g&&(g=g[d],a=w(a),g[a]))){a=g[a];break a}a=k}if(a)for(g=0;g<a.length;g++)if(a[g].Fa==c&&a[g].capture==d&&a[g].ob==e){tc(a[g].key);break}}}
function tc(a){if(!pc[a])return n;var b=pc[a];if(b.qa)return n;var c=b.src,d=b.type,e=b.cc,g=b.capture;c.removeEventListener?(c==s||!c.Fb)&&c.removeEventListener(d,e,g):c.detachEvent&&c.detachEvent(d in qc?qc[d]:qc[d]="on"+d,e);c=w(c);e=R[d][g][c];if(C[c]){var i=C[c],l=za(i,b);l>=0&&B.splice.call(i,l,1);i.length==0&&delete C[c]}b.qa=j;e.Wb=j;uc(d,g,c,e);delete pc[a];return j}
function uc(a,b,c,d){if(!d.Va&&d.Wb){for(var e=0,g=0;e<d.length;e++)if(d[e].qa){var i=d[e].cc;i.src=k;kc(i);mc(d[e])}else e!=g&&(d[g]=d[e]),g++;d.length=g;d.Wb=n;g==0&&(hc(d),delete R[a][b][c],R[a][b].e--,R[a][b].e==0&&(fc(R[a][b]),delete R[a][b],R[a].e--),R[a].e==0&&(fc(R[a]),delete R[a]))}}
function vc(a){var b,c=0,d=b==k;b=!!b;if(a==k)Ea(function(a){for(var e=a.length-1;e>=0;e--){var g=a[e];if(d||b==g.capture)tc(g.key),c++}});else if(a=w(a),C[a])for(var a=C[a],e=a.length-1;e>=0;e--){var g=a[e];if(d||b==g.capture)tc(g.key),c++}}function wc(a,b,c,d,e){var g=1,b=w(b);if(a[b]){a.C--;a=a[b];a.Va?a.Va++:a.Va=1;try{for(var i=a.length,l=0;l<i;l++){var m=a[l];m&&!m.qa&&(g&=xc(m,e)!==n)}}finally{a.Va--,uc(c,d,b,a)}}return Boolean(g)}
function xc(a,b){var c=a.handleEvent(b);a.Ab&&tc(a.key);return c}
jc(function(a,b){if(!pc[a])return j;var c=pc[a],d=c.type,e=R;if(!(d in e))return j;var e=e[d],g,i;Ab===h&&(Ab=P&&!s.addEventListener);if(Ab){g=b||ca("window.event");var l=j in e,m=n in e;if(l){if(g.keyCode<0||g.returnValue!=h)return j;a:{var o=n;if(g.keyCode==0)try{g.keyCode=-1;break a}catch(x){o=j}if(o||g.returnValue==h)g.returnValue=j}}o=nc();o.Ua(g,this);g=j;try{if(l){for(var r=gc(),E=o.currentTarget;E;E=E.parentNode)r.push(E);i=e[j];i.C=i.e;for(var F=r.length-1;!o.pa&&F>=0&&i.C;F--)o.currentTarget=
r[F],g&=wc(i,r[F],d,j,o);if(m){i=e[n];i.C=i.e;for(F=0;!o.pa&&F<r.length&&i.C;F++)o.currentTarget=r[F],g&=wc(i,r[F],d,n,o)}}else g=xc(c,o)}finally{if(r)r.length=0,hc(r);o.la();oc(o)}return g}d=new Xb(b,this);try{g=xc(c,d)}finally{d.la()}return g});function yc(){}A(yc,N);q=yc.prototype;q.Fb=j;q.tb=k;q.addEventListener=function(a,b,c,d){rc(this,a,b,c,d)};q.removeEventListener=function(a,b,c,d){sc(this,a,b,c,d)};
q.dispatchEvent=function(a){var b=a.type||a,c=R;if(b in c){if(v(a))a=new O(a,this);else if(a instanceof O)a.target=a.target||this;else{var d=a,a=new O(b,this);Ia(a,d)}var d=1,e,c=c[b],b=j in c,g;if(b){e=[];for(g=this;g;g=g.tb)e.push(g);g=c[j];g.C=g.e;for(var i=e.length-1;!a.pa&&i>=0&&g.C;i--)a.currentTarget=e[i],d&=wc(g,e[i],a.type,j,a)&&a.$a!=n}if(n in c)if(g=c[n],g.C=g.e,b)for(i=0;!a.pa&&i<e.length&&g.C;i++)a.currentTarget=e[i],d&=wc(g,e[i],a.type,n,a)&&a.$a!=n;else for(e=this;!a.pa&&e&&g.C;e=e.tb)a.currentTarget=
e,d&=wc(g,e,a.type,n,a)&&a.$a!=n;a=Boolean(d)}else a=j;return a};q.r=function(){yc.$.r.call(this);vc(this);this.tb=k};function zc(a){return eval("("+a+")")}function Ac(){}function Bc(a){var b=[];Cc(new Ac,a,b);return b.join("")}
function Cc(a,b,c){switch(typeof b){case "string":Dc(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==k){c.push("null");break}if(u(b)){var d=b.length;c.push("[");for(var e="",g=0;g<d;g++)c.push(e),Cc(a,b[g],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(g=b[e],typeof g!="function"&&(c.push(d),Dc(e,c),c.push(":"),Cc(a,g,c),d=","));c.push("}");
break;case "function":break;default:f(Error("Unknown type: "+typeof b))}}var Ec={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},Fc=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function Dc(a,b){b.push('"',a.replace(Fc,function(a){if(a in Ec)return Ec[a];var b=a.charCodeAt(0),e="\\u";b<16?e+="000":b<256?e+="00":b<4096&&(e+="0");return Ec[a]=e+b.toString(16)}),'"')};function Gc(a,b){this.Aa=a||1;this.Ja=b||Hc;this.hb=y(this.Hc,this);this.sb=z()}A(Gc,yc);Gc.prototype.enabled=n;var Hc=s.window;q=Gc.prototype;q.T=k;q.setInterval=function(a){this.Aa=a;this.T&&this.enabled?(this.stop(),this.start()):this.T&&this.stop()};q.Hc=function(){if(this.enabled){var a=z()-this.sb;if(a>0&&a<this.Aa*0.8)this.T=this.Ja.setTimeout(this.hb,this.Aa-a);else if(this.dispatchEvent(Ic),this.enabled)this.T=this.Ja.setTimeout(this.hb,this.Aa),this.sb=z()}};
q.start=function(){this.enabled=j;if(!this.T)this.T=this.Ja.setTimeout(this.hb,this.Aa),this.sb=z()};q.stop=function(){this.enabled=n;if(this.T)this.Ja.clearTimeout(this.T),this.T=k};q.r=function(){Gc.$.r.call(this);this.stop();delete this.Ja};var Ic="tick";function Jc(a){this.i=a;this.k=[]}A(Jc,N);var Kc=[];Jc.prototype.r=function(){Jc.$.r.call(this);Aa(this.k,tc);this.k.length=0};Jc.prototype.handleEvent=function(){f(Error("EventHandler.handleEvent not implemented"))};function Lc(){}Lc.prototype.Na=k;function Mc(){return Nc(Oc)}var Oc;function Pc(){}A(Pc,Lc);function Nc(a){return(a=Qc(a))?new ActiveXObject(a):new XMLHttpRequest}function Rc(a){var b={};Qc(a)&&(b[0]=j,b[1]=j);return b}Pc.prototype.pb=k;
function Qc(a){if(!a.pb&&typeof XMLHttpRequest=="undefined"&&typeof ActiveXObject!="undefined"){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.pb=d}catch(e){}}f(Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed"))}return a.pb}Oc=new Pc;function S(a,b,c,d,e){this.h=a;this.a=b;this.Z=c;this.A=d;this.Ha=e||1;this.Ia=Sc;this.Kb=new Jc(this);this.Ya=new Gc;this.Ya.setInterval(Tc)}q=S.prototype;q.t=k;q.D=n;q.wa=k;q.xb=k;q.ra=k;q.Ka=k;q.V=k;q.v=k;q.X=k;q.o=k;q.Ma=0;q.F=k;q.ua=k;q.p=k;q.j=-1;q.gc=j;q.ja=n;var Sc=45E3,Tc=250;function Uc(a,b){switch(a){case 0:return"Non-200 return code ("+b+")";case 1:return"XMLHTTP failure (no data)";case 2:return"HttpConnection timeout";default:return"Unknown error"}}var Vc={},Wc={};q=S.prototype;q.Y=p("t");
q.setTimeout=p("Ia");function Xc(a,b,c){a.Ka=1;a.V=J(b.n());a.X=c;a.Gb=j;Yc(a,k)}function Zc(a,b,c,d,e){a.Ka=1;a.V=J(b.n());a.X=k;a.Gb=c;if(e)a.gc=n;Yc(a,d)}
function Yc(a,b){a.v=a.V.n();eb(a.v,"t",a.Ha);a.Ma=0;a.o=a.h.lb(a.h.ab()?b:k);rc(a.o,"readystatechange",a.kc,n,a);var c;if(a.t){c=a.t;var d={},e;for(e in c)d[e]=c[e];c=d}else c={};a.X?(a.ua="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.o.send(a.v,a.ua,a.X,c)):(a.ua="GET",a.gc&&!Kb&&(c.Connection="close"),a.o.send(a.v,a.ua,k,c));a.ra=z();if(d=a.X){c="";d=d.split("&");for(e=0;e<d.length;e++){var g=d[e].split("=");if(g.length>1){var i=g[0],g=g[1],l=i.split("_");c+=l.length>=2&&l[1]==
"type"?i+"="+g+"&":i+"=redacted&"}}}else c=k;a.a.info("XMLHTTP REQ ("+a.A+") [attempt "+a.Ha+"]: "+a.ua+"\n"+a.v+"\n"+c);$c(a)}
q.kc=function(a){a=a.target;try{if(a==this.o)a:{var b=T(this.o);if(P||Kb&&!Ub["420+"]&&!(Ub["420+"]=va(Nb,"420+")>=0)){if(b<4)break a}else if(b<3||b==3&&!Ib&&!ad(this.o))break a;bd(this);var c=cd(this.o);this.j=c;var d=ad(this.o);d||this.a.info("No response text for uri "+this.v+" status "+c);this.D=c==200;this.a.info("XMLHTTP RESP ("+this.A+") [ attempt "+this.Ha+"]: "+this.ua+"\n"+this.v+"\n"+b+" "+c);if(this.D){b==4&&dd(this);if(this.Gb){if(ed(this,b,d),Ib&&b==3){var e=this.Kb,g=this.Ya,i=this.Ec,
c=Ic;u(c)||(Kc[0]=c,c=Kc);for(d=0;d<c.length;d++)e.k.push(rc(g,c[d],i||e,n,e.i||e));this.Ya.start()}}else fd(this.a,this.A,d,k),gd(this,d);if(this.D&&!this.ja)b==4?this.h.Wa(this):(this.D=n,$c(this))}else c==400&&d.indexOf("Unknown SID")>0?(this.p=3,U(hd)):(this.p=0,U(id)),fd(this.a,this.A,d),dd(this),jd(this)}else this.a.va("Called back with an unexpected xmlhttp")}catch(l){this.a.info("Failed call to OnXmlHttpReadyStateChanged_"),this.o&&ad(this.o)?V(this.a,l,"ResponseText: "+ad(this.o)):V(this.a,
l,"No response text")}finally{}};function ed(a,b,c){for(var d=j;!a.ja&&a.Ma<c.length;){var e=kd(a,c);if(e==Wc){if(b==4)a.p=4,U(ld),d=n;fd(a.a,a.A,k,"[Incomplete Response]");break}else if(e==Vc){a.p=4;U(md);fd(a.a,a.A,c,"[Invalid Chunk]");d=n;break}else fd(a.a,a.A,e,k),gd(a,e)}if(b==4&&c.length==0)a.p=1,U(nd),d=n;a.D=a.D&&d;d||(fd(a.a,a.A,c,"[Invalid Chunked Response]"),dd(a),jd(a))}q.Ec=function(){var a=T(this.o),b=ad(this.o);this.Ma<b.length&&(bd(this),ed(this,a,b),this.D&&a!=4&&$c(this))};
function kd(a,b){var c=a.Ma,d=b.indexOf("\n",c);if(d==-1)return Wc;c=Number(b.substring(c,d));if(isNaN(c))return Vc;d+=1;if(d+c>b.length)return Wc;var e=b.substr(d,c);a.Ma=d+c;return e}
function od(a,b){a.F=new ActiveXObject("htmlfile");var c="",d="<html><body>";if(b)c=window.location.hostname,d+='<script>document.domain="'+c+'"<\/script>';d+="</body></html>";a.F.open();a.F.write(d);a.F.close();a.F.parentWindow.m=y(a.Bc,a);a.F.parentWindow.d=y(a.bc,a,j);a.F.parentWindow.rpcClose=y(a.bc,a,n);d=a.F.createElement("div");a.F.parentWindow.document.body.appendChild(d);a.v=a.V.n();G(a.v,"DOMAIN",c);G(a.v,"t",a.Ha);d.innerHTML='<iframe src="'+a.v+'"></iframe>';a.ra=z();a.a.info("TRIDENT REQ ("+
a.A+") [ attempt "+a.Ha+"]: GET\n"+a.v);$c(a)}q.Bc=function(a){W(y(this.Ac,this,a),0)};q.Ac=function(a){if(!this.ja){var b=this.a;b.info("TRIDENT TEXT ("+this.A+"): "+pd(b,a));bd(this);gd(this,a);$c(this)}};q.bc=function(a){W(y(this.zc,this,a),0)};q.zc=function(a){if(!this.ja)this.a.info("TRIDENT TEXT ("+this.A+"): "+a?"success":"failure"),bd(this),dd(this),this.D=a,this.h.Wa(this)};q.cancel=function(){this.ja=j;bd(this);dd(this)};function $c(a){a.xb=z()+a.Ia;qd(a,a.Ia)}
function qd(a,b){a.wa!=k&&f(Error("WatchDog timer not null"));a.wa=W(y(a.Cc,a),b)}function bd(a){if(a.wa)s.clearTimeout(a.wa),a.wa=k}q.Cc=function(){this.wa=k;var a=z();a-this.xb>=0?(this.D&&this.a.I("Received watchdog timeout even though request loaded successfully"),this.a.info("TIMEOUT: "+this.v),dd(this),this.p=2,U(rd),jd(this)):(this.a.va("WatchDog timer called too early"),qd(this,this.xb-a))};function jd(a){!a.h.Qb()&&!a.ja&&a.h.Wa(a)}
function dd(a){a.Ya.stop();var b=a.Kb;Aa(b.k,tc);b.k.length=0;if(a.o)b=a.o,a.o=k,sc(b,"readystatechange",a.kc,n,a),b.abort();if(a.F)a.F=k}q.Ob=aa("p");function gd(a,b){try{a.h.Zb(a,b)}catch(c){V(a.a,c,"Error in httprequest callback")}};function sd(){this.g=xb("goog.net.BrowserChannel")}function fd(a,b,c,d){a.info("XMLHTTP TEXT ("+b+"): "+pd(a,c)+(d?" "+d:""))}function td(a,b){a.info(b)}function V(a,b,c){a.I((c||"Exception")+b)}sd.prototype.info=function(a){this.g.info(a)};sd.prototype.va=function(a){this.g.va(a)};sd.prototype.I=function(a){this.g.I(a)};
function pd(a,b){if(!b||b==ud)return b;try{for(var c=zc(b),d=0;d<c.length;d++)if(u(c[d])){var e=c[d];if(!(e.length<2)){var g=e[1];if(u(g)&&!(g.length<1)){var i=g[0];if(i!="noop"&&i!="stop")for(var l=1;l<g.length;l++)g[l]=""}}}return Bc(c)}catch(m){return a.info("Exception parsing expected JS array - probably was not JS"),b}};function vd(a,b,c,d,e){td(new sd,"TestLoadImageWithRetries: "+e);if(d==0)c(n);else{var g=e||0;d--;wd(a,b,function(e){e?c(j):s.setTimeout(function(){vd(a,b,c,d,g)},g)})}}
function wd(a,b,c){var d=new sd;d.info("TestLoadImage: loading "+a);var e=new Image;e.onload=function(){try{d.info("TestLoadImage: loaded"),xd(e),c(j)}catch(a){V(d,a)}};e.onerror=function(){try{d.info("TestLoadImage: error"),xd(e),c(n)}catch(a){V(d,a)}};e.onabort=function(){try{d.info("TestLoadImage: abort"),xd(e),c(n)}catch(a){V(d,a)}};e.ontimeout=function(){try{d.info("TestLoadImage: timeout"),xd(e),c(n)}catch(a){V(d,a)}};s.setTimeout(function(){if(e.ontimeout)e.ontimeout()},b);e.src=a}
function xd(a){a.onload=k;a.onerror=k;a.onabort=k;a.ontimeout=k};function yd(a,b){this.h=a;this.a=b}q=yd.prototype;q.t=k;q.w=k;q.Za=n;q.ic=k;q.Ra=k;q.rb=k;q.q=k;q.b=k;q.j=-1;q.P=k;q.gb=k;q.Y=p("t");q.Oa=function(a){this.q=a;a=zd(this.h,this.q);U(Ad);eb(a,"MODE","init");this.w=new S(this,this.a,h,h,h);this.w.Y(this.t);Zc(this.w,a,n,k,j);this.b=0;this.ic=z()};q.nc=function(a){a?(this.b=2,Bd(this)):(U(Cd),a=this.h,a.a.info("Test Connection Blocked"),a.j=a.aa.j,X(a,9))};
function Bd(a){a.a.info("TestConnection: starting stage 2");a.w=new S(a,a.a,h,h,h);a.w.Y(a.t);var b=Dd(a.h,a.P,a.q);U(Ed);if(P){eb(b,"TYPE","html");var c=a.w,a=Boolean(a.P);c.Ka=3;c.V=J(b.n());od(c,a)}else eb(b,"TYPE","xmlhttp"),Zc(a.w,b,n,a.P,n)}q.lb=function(a){return this.h.lb(a)};q.abort=function(){if(this.w)this.w.cancel(),this.w=k;this.j=-1};q.Qb=function(){return n};
q.Zb=function(a,b){this.j=a.j;if(this.b==0)if(this.a.info("TestConnection: Got data for stage 1"),b){try{var c=zc(b)}catch(d){V(this.a,d);Fd(this.h,this);return}this.P=this.h.Pa(c[0]);this.gb=c[1]}else this.a.info("TestConnection: Null responseText"),Fd(this.h,this);else if(this.b==2)if(this.Za)U(Gd),this.rb=z();else if(b=="11111"){if(U(Hd),this.Za=j,this.Ra=z(),c=this.Ra-this.ic,!P||c<500)this.j=200,this.w.cancel(),this.a.info("Test connection succeeded; using streaming connection"),U(Id),Jd(this.h,
this,j)}else U(Kd),this.Ra=this.rb=z(),this.Za=n};
q.Wa=function(){this.j=this.w.j;if(this.w.D)if(this.b==0)if(this.a.info("TestConnection: request complete for initial check"),this.gb){this.b=1;var a=Ld(this.h,this.gb,"/mail/images/cleardot.gif");J(a);vd(a.toString(),5E3,y(this.nc,this),3,2E3)}else this.b=2,Bd(this);else this.b==2&&(this.a.info("TestConnection: request complete for stage 2"),a=n,(a=P?this.rb-this.Ra<200?n:j:this.Za)?(this.a.info("Test connection succeeded; using streaming connection"),U(Id),Jd(this.h,this,j)):(this.a.info("Test connection failed; not using streaming"),
U(Md),Jd(this.h,this,n)));else this.a.info("TestConnection: request failed, in state "+this.b),this.b==0?U(Nd):this.b==2&&U(Od),Fd(this.h,this)};q.ab=function(){return this.h.ab()};q.oa=function(){return this.h.oa()};function Pd(){if(Jb)this.ba={},this.fb={},this.bb=[]}Pd.prototype.g=xb("goog.net.xhrMonitor");Pd.prototype.Qa=Jb;function Qd(a){var b=Rd;if(b.Qa){var c=v(a)?a:ga(a)?w(a):"";b.g.log(tb,"Pushing context: "+a+" ("+c+")",h);b.bb.push(c)}}function Sd(){var a=Rd;if(a.Qa){var b=a.bb.pop();a.g.log(tb,"Popping context: "+b,h);Td(a,b)}}function Ud(a){var b=Rd;if(b.Qa){a=w(a);M(b.g,"Opening XHR : "+a);for(var c=0;c<b.bb.length;c++){var d=b.bb[c];Vd(b.ba,d,a);Vd(b.fb,a,d)}}}
function Td(a,b){var c=a.fb[b],d=a.ba[b];c&&d&&(a.g.log(tb,"Updating dependent contexts",h),Aa(c,function(a){Aa(d,function(b){Vd(this.ba,a,b);Vd(this.fb,b,a)},this)},a))}function Vd(a,b,c){a[b]||(a[b]=[]);za(a[b],c)>=0||a[b].push(c)}var Rd=new Pd;function Y(a){this.headers=new La;this.xa=a||k}A(Y,yc);Y.prototype.g=xb("goog.net.XhrIo");var Wd=/^https?:?$/i;q=Y.prototype;q.U=n;q.c=k;q.eb=k;q.Da="";q.Sb="";q.Ca=0;q.p="";q.nb=n;q.Ta=n;q.qb=n;q.fa=n;q.cb=0;q.ha=k;q.fc="";q.Ic=n;
q.send=function(a,b,c,d){this.c&&f(Error("[goog.net.XhrIo] Object is active with another request"));b=b?b.toUpperCase():"GET";this.Da=a;this.p="";this.Ca=0;this.Sb=b;this.nb=n;this.U=j;this.c=this.xa?Nc(this.xa):new Mc;this.eb=this.xa?this.xa.Na||(this.xa.Na=Rc(this.xa)):Oc.Na||(Oc.Na=Rc(Oc));Ud(this.c);this.c.onreadystatechange=y(this.Yb,this);try{M(this.g,Z(this,"Opening Xhr")),this.qb=j,this.c.open(b,a,j),this.qb=n}catch(e){M(this.g,Z(this,"Error opening Xhr: "+e.message));Xd(this,e);return}var a=
c||"",g=this.headers.n();d&&Ka(d,function(a,b){g.set(b,a)});b=="POST"&&!g.K("Content-Type")&&g.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");Ka(g,function(a,b){this.c.setRequestHeader(b,a)},this);if(this.fc)this.c.responseType=this.fc;if("withCredentials"in this.c)this.c.withCredentials=this.Ic;try{if(this.ha)Hc.clearTimeout(this.ha),this.ha=k;if(this.cb>0)M(this.g,Z(this,"Will abort after "+this.cb+"ms if incomplete")),this.ha=Hc.setTimeout(y(this.Ia,this),this.cb);M(this.g,
Z(this,"Sending request"));this.Ta=j;this.c.send(a);this.Ta=n}catch(i){M(this.g,Z(this,"Send error: "+i.message)),Xd(this,i)}};q.dispatchEvent=function(a){if(this.c){Qd(this.c);try{return Y.$.dispatchEvent.call(this,a)}finally{Sd()}}else return Y.$.dispatchEvent.call(this,a)};q.Ia=function(){if(typeof ba!="undefined"&&this.c)this.p="Timed out after "+this.cb+"ms, aborting",this.Ca=8,M(this.g,Z(this,this.p)),this.dispatchEvent("timeout"),this.abort(8)};
function Xd(a,b){a.U=n;if(a.c)a.fa=j,a.c.abort(),a.fa=n;a.p=b;a.Ca=5;Yd(a);Zd(a)}function Yd(a){if(!a.nb)a.nb=j,a.dispatchEvent("complete"),a.dispatchEvent("error")}q.abort=function(a){if(this.c&&this.U)M(this.g,Z(this,"Aborting")),this.U=n,this.fa=j,this.c.abort(),this.fa=n,this.Ca=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Zd(this)};q.r=function(){if(this.c){if(this.U)this.U=n,this.fa=j,this.c.abort(),this.fa=n;Zd(this,j)}Y.$.r.call(this)};
q.Yb=function(){!this.qb&&!this.Ta&&!this.fa?this.yc():$d(this)};q.yc=function(){$d(this)};
function $d(a){if(a.U&&typeof ba!="undefined")if(a.eb[1]&&T(a)==4&&cd(a)==2)M(a.g,Z(a,"Local request error detected and ignored"));else if(a.Ta&&T(a)==4)Hc.setTimeout(y(a.Yb,a),0);else if(a.dispatchEvent("readystatechange"),T(a)==4){M(a.g,Z(a,"Request complete"));a.U=n;var b;a:switch(cd(a)){case 0:b=v(a.Da)?a.Da.match(Oa)[1]||k:a.Da.S;b=!(b?Wd.test(b):self.location?Wd.test(self.location.protocol):1);break a;case 200:case 204:case 304:case 1223:b=j;break a;default:b=n}if(b)a.dispatchEvent("complete"),
a.dispatchEvent("success");else{a.Ca=6;var c;try{c=T(a)>2?a.c.statusText:""}catch(d){M(a.g,"Can not get status: "+d.message),c=""}a.p=c+" ["+cd(a)+"]";Yd(a)}Zd(a)}}
function Zd(a,b){if(a.c){var c=a.c,d=a.eb[0]?t:k;a.c=k;a.eb=k;if(a.ha)Hc.clearTimeout(a.ha),a.ha=k;b||(Qd(c),a.dispatchEvent("ready"),Sd());var e=Rd;if(e.Qa){var g=w(c);M(e.g,"Closing XHR : "+g);delete e.fb[g];for(var i in e.ba){var l=e.ba[i],m=za(l,g);m>=0&&B.splice.call(l,m,1);e.ba[i].length==0&&delete e.ba[i]}}try{c.onreadystatechange=d}catch(o){a.g.I("Problem encountered resetting onreadystatechange: "+o.message)}}}q.oa=function(){return!!this.c};function T(a){return a.c?a.c.readyState:0}
function cd(a){try{return T(a)>2?a.c.status:-1}catch(b){return a.g.va("Can not get status: "+b.message),-1}}function ad(a){try{return a.c?a.c.responseText:""}catch(b){return M(a.g,"Can not get responseText: "+b.message),""}}q.Ob=function(){return v(this.p)?this.p:String(this.p)};function Z(a,b){return b+" ["+a.Sb+" "+a.Da+" "+cd(a)+"]"};function ae(a){this.Eb=a;this.b=be;this.s=[];this.R=[];this.a=new sd}function ce(a,b){this.Ub=a;this.map=b}q=ae.prototype;q.t=k;q.ya=k;q.u=k;q.l=k;q.q=k;q.Sa=k;q.zb=k;q.P=k;q.mc=j;q.Ga=0;q.wc=0;q.qc=n;q.i=k;q.W=k;q.J=k;q.ca=k;q.aa=k;q.wb=k;q.lc=j;q.Ba=-1;q.Tb=-1;q.j=-1;q.ma=0;q.ia=0;q.ka=8;var be=1,de=new yc;function ee(a,b){O.call(this,"statevent",a);this.Oc=b}A(ee,O);function fe(a,b,c,d){O.call(this,"timingevent",a);this.size=b;this.Nc=c;this.Mc=d}A(fe,O);
var Ad=3,Cd=4,Ed=5,Hd=6,Gd=7,Kd=8,Nd=9,Od=10,Md=11,Id=12,hd=13,id=14,ld=15,md=16,nd=17,rd=18,ud="y2f%";q=ae.prototype;q.Oa=function(a,b,c,d,e){this.a.info("connect()");U(0);this.q=b;this.ya=c||{};if(d&&e!==h)this.ya.OSID=d,this.ya.OAID=e;this.a.info("connectTest_()");this.aa=new yd(this,this.a);this.aa.Y(this.t);this.aa.Oa(a)};
q.Hb=function(){this.a.info("disconnect()");ge(this);if(this.b==3){var a=this.Ga++,b=this.Sa.n();G(b,"SID",this.Z);G(b,"RID",a);G(b,"TYPE","terminate");he(this,b);a=new S(this,this.a,this.Z,a,h);a.Ka=2;a.V=J(b.n());(new Image).src=a.V;a.ra=z();$c(a);ie(this)}};function ge(a){if(a.aa)a.aa.abort(),a.aa=k;if(a.l)a.l.cancel(),a.l=k;if(a.J)s.clearTimeout(a.J),a.J=k;je(a);if(a.u)a.u.cancel(),a.u=k;if(a.W)s.clearTimeout(a.W),a.W=k}q.Y=p("t");
q.ub=function(a){this.b==0&&f(Error("Invalid operation: sending map when state is closed"));this.s.length==1E3&&this.a.I("Already have 1000 queued maps upon queueing "+Bc(a));this.s.push(new ce(this.wc++,a));(this.b==2||this.b==3)&&ke(this)};q.Qb=function(){return this.b==0};function ke(a){if(!a.u&&!a.W)a.W=W(y(a.ac,a),0),a.ma=0}
q.ac=function(a){this.W=k;this.a.info("startForwardChannel_");if(this.b==be)if(a)this.a.I("Not supposed to retry the open");else{this.a.info("open_()");this.Ga=Math.floor(Math.random()*1E5);var a=this.Ga++,b=new S(this,this.a,"",a,h);b.Y(this.t);var c=le(this),d=this.Sa.n();G(d,"RID",a);this.Eb&&G(d,"CVER",this.Eb);he(this,d);Xc(b,d,c);this.u=b;this.b=2}else this.b==3&&(a?me(this,a):this.s.length==0?this.a.info("startForwardChannel_ returned: nothing to send"):this.u?this.a.I("startForwardChannel_ returned: connection already in progress"):
(me(this),this.a.info("startForwardChannel_ finished, sent request")))};function me(a,b){var c,d;b?a.ka>6?(a.s=a.R.concat(a.s),a.R.length=0,c=a.Ga-1,d=le(a)):(c=b.A,d=b.X):(c=a.Ga++,d=le(a));var e=a.Sa.n();G(e,"SID",a.Z);G(e,"RID",c);G(e,"AID",a.Ba);he(a,e);c=new S(a,a.a,a.Z,c,a.ma+1);c.Y(a.t);c.setTimeout(Math.round(1E4)+Math.round(1E4*Math.random()));a.u=c;Xc(c,e,d)}function he(a,b){a.i&&Ka({},function(a,d){G(b,d,a)})}
function le(a){var b=Math.min(a.s.length,1E3),c=["count="+b],d;a.ka>6&&b>0?(d=a.s[0].Ub,c.push("ofs="+d)):d=0;for(var e=0;e<b;e++){var g=a.s[e].Ub,i=a.s[e].map;a.ka<=6?g=e:g-=d;try{Ka(i,function(a,b){c.push("req"+g+"_"+b+"="+encodeURIComponent(a))})}catch(l){c.push("req"+g+"_type="+encodeURIComponent("_badmap"))}}a.R=a.R.concat(a.s.splice(0,b));return c.join("&")}function ne(a){if(!a.l&&!a.J)a.yb=1,a.J=W(y(a.$b,a),0),a.ia=0}
function oe(a){if(a.l||a.J)return a.a.I("Request already in progress"),n;if(a.ia>=3)return n;a.a.info("Going to retry GET");a.yb++;a.J=W(y(a.$b,a),pe(a,a.ia));a.ia++;return j}
q.$b=function(){this.J=k;this.a.info("Creating new HttpRequest");this.l=new S(this,this.a,this.Z,"rpc",this.yb);this.l.Y(this.t);var a=this.zb.n();G(a,"RID","rpc");G(a,"SID",this.Z);G(a,"CI",this.wb?"0":"1");G(a,"AID",this.Ba);he(this,a);if(P){G(a,"TYPE","html");var b=this.l,c=Boolean(this.P);b.Ka=3;b.V=J(a.n());od(b,c)}else G(a,"TYPE","xmlhttp"),Zc(this.l,a,j,this.P,n);this.a.info("New Request created")};
function Jd(a,b,c){a.a.info("Test Connection Finished");a.wb=a.lc&&c;a.j=b.j;a.a.info("connectChannel_()");a.pc(be,0);a.Sa=zd(a,a.q);ke(a)}function Fd(a,b){a.a.info("Test Connection Failed");a.j=b.j;X(a,2)}
q.Zb=function(a,b){if(!(this.b==0||this.l!=a&&this.u!=a))if(this.j=a.j,this.u==a&&this.b==3)if(this.ka>7){var c;try{c=zc(b)}catch(d){c=k}if(u(c)&&c.length==3){var e=c;if(e[0]==0)a:if(this.a.info("Server claims our backchannel is missing."),this.J)this.a.info("But we are currently starting the request.");else{if(this.l)if(this.l.ra+3E3<this.u.ra)je(this),this.l.cancel(),this.l=k;else break a;else this.a.va("We do not have a BackChannel established");oe(this);U(19)}else if(this.Tb=e[1],c=this.Tb-this.Ba,
0<c&&(e=e[2],this.a.info(e+" bytes (in "+c+" arrays) are outstanding on the BackChannel"),e<37500&&this.wb&&this.ia==0&&!this.ca))this.ca=W(y(this.xc,this),6E3)}else this.a.info("Bad POST response data returned"),X(this,11)}else b!=ud&&(this.a.info("Bad data returned - missing/invald magic cookie"),X(this,11));else if(this.l==a&&je(this),!/^[\s\xa0]*$/.test(b)){c=zc(b);for(var e=this.i&&this.i.jb?[]:k,g=0;g<c.length;g++){var i=c[g];this.Ba=i[0];i=i[1];if(this.b==2)i[0]=="c"?(this.Z=i[1],this.P=this.Pa(i[2]),
i=i[3],this.ka=i!=k?i:6,this.b=3,this.i&&this.i.Db(this),this.zb=Dd(this,this.P,this.q),ne(this)):i[0]=="stop"&&X(this,7);else if(this.b==3){if(i[0]=="stop"){if(e&&e.length)this.i.jb(this,e),e.length=0;X(this,7)}else i[0]!="noop"&&(e?e.push(i):this.i&&this.i.Cb(this,i));this.ia=0}}e&&e.length&&this.i.jb(this,e)}};q.Pa=function(a){return this.mc?this.i?this.i.Pa(a):a:k};q.xc=function(){if(this.ca!=k)this.ca=k,this.l.cancel(),this.l=k,oe(this),U(20)};
function je(a){if(a.ca!=k)s.clearTimeout(a.ca),a.ca=k}
q.Wa=function(a){this.a.info("Request complete");var b;if(this.l==a)je(this),this.l=k,b=2;else if(this.u==a)this.u=k,b=1;else return;this.j=a.j;if(this.b!=0)if(a.D)b==1?(b=z()-a.ra,de.dispatchEvent(new fe(de,a.X?a.X.length:0,b,this.ma)),ke(this),this.R.length=0):ne(this);else{var c=a.Ob();if(c==3||c==0&&this.j>0)this.a.info("Not retrying due to error type");else{this.a.info("Maybe retrying, last error: "+Uc(c,this.j));var d;if(d=b==1)this.u||this.W?(this.a.I("Request already in progress"),d=n):this.b==
be||this.ma>=(this.qc?0:2)?d=n:(this.a.info("Going to retry POST"),this.W=W(y(this.ac,this,a),pe(this,this.ma)),this.ma++,d=j);if(d)return;if(b==2&&oe(this))return;this.a.info("Exceeded max number of retries")}this.a.info("Error: HTTP request failed");switch(c){case 1:X(this,5);break;case 4:X(this,10);break;case 3:X(this,6);break;default:X(this,2)}}};function pe(a,b){var c=5E3+Math.floor(Math.random()*1E4);a.oa()||(a.a.info("Inactive channel"),c*=2);c*=b;return c}
q.pc=function(a){za(arguments,this.b)>=0||f(Error("Unexpected channel state: "+this.b))};function X(a,b){a.a.info("Error code "+b);if(b==2||b==9){var c=k;a.i&&(c=k);var d=y(a.Gc,a);c||(c=new Pa("//www.google.com/images/cleardot.gif"),J(c));wd(c.toString(),1E4,d)}else U(2);qe(a,b)}q.Gc=function(a){a?(this.a.info("Successfully pinged google.com"),U(2)):(this.a.info("Failed to ping google.com"),U(1),qe(this,8))};
function qe(a,b){a.a.info("HttpChannel: error - "+b);a.b=0;a.i&&a.i.Bb(a,b);ie(a);ge(a)}function ie(a){a.b=0;a.j=-1;if(a.i)if(a.R.length==0&&a.s.length==0)a.i.ib(a);else{a.a.info("Number of undelivered maps, pending: "+a.R.length+", outgoing: "+a.s.length);var b=Ca(a.R),c=Ca(a.s);a.R.length=0;a.s.length=0;a.i.ib(a,b,c)}}function zd(a,b){var c=Ld(a,k,b);a.a.info("GetForwardChannelUri: "+c);return c}function Dd(a,b,c){b=Ld(a,a.ab()?b:k,c);a.a.info("GetBackChannelUri: "+b);return b}
function Ld(a,b,c){var d=c instanceof Pa?c.n():new Pa(c,h);if(d.M!="")b&&Sa(d,b+"."+d.M),Ta(d,d.ga);else var e=window.location,d=cb(e.protocol,k,b?b+"."+e.hostname:e.hostname,e.port,c);a.ya&&Ka(a.ya,function(a,b){G(d,b,a)});G(d,"VER",a.ka);he(a,d);return d}q.lb=function(a){if(a)f(Error("Can't create secondary domain capable XhrIo object."));else return new Y};q.oa=function(){return!!this.i&&this.i.oa(this)};
function W(a,b){fa(a)||f(Error("Fn must not be null and must be a function"));return s.setTimeout(function(){a()},b)}function U(a){de.dispatchEvent(new ee(de,a))}q.ab=function(){return P};function re(){}q=re.prototype;q.jb=k;q.Db=function(){};q.Cb=function(){};q.Bb=function(){};q.ib=function(){};q.oa=function(){return j};q.Pa=function(a){return a};var se,te;function $(a,b){return function(){return a.apply(b,arguments)}}var ue=Array.prototype.slice;te=(typeof process!=="undefined"&&process!==k?process.nextTick:h)||function(a){return setTimeout(a,0)};
se=function(){function a(){}a.prototype.Xb=function(a,c){var d;this.G||(this.G={});(d=this.G)[a]||(d[a]=[]);this.G[a].push(c);return this};a.prototype.ec=function(a,c){var d,e;this.G||(this.G={});e=(d=this.G)[a]||(d[a]=[]);for(d=0;d<e.length;)e[d]===c&&(e[d]=h),d++;te($(function(){var c,d=this.G,e,m,o,x;o=this.G[a];x=[];for(e=0,m=o.length;e<m;e++)(c=o[e])&&x.push(c);return d[a]=x},this));return this};a.prototype.N=function(){var a,c,d,e,g;c=arguments[0];a=2<=arguments.length?ue.call(arguments,1):
[];if(!((d=this.G)!=k&&d[c]))return this;g=this.G[c];for(d=0,e=g.length;d<e;d++)(c=g[d])&&c.apply(this,a);return this};return a}();se.tc=function(){var a=ve,a=a.prototype||a;a.on=a.Xb=se.prototype.Xb;a.removeListener=a.ec=se.prototype.ec;a.emit=a.N=se.prototype.N};var ve,we,$=function(a,b){return function(){return a.apply(b,arguments)}};
we={0:"Ok",4:"User is being logged out",6:"Unknown session ID",7:"Stopped by server",8:"General network error",2:"Request failed",9:"The channel has been blocked by a network administrator",5:"No data from server",10:"Got bad data from the server",11:"Got a bad response from the server"};
ve=function(a,b,c){var d,e,g,i,l,m;a||(a="channel");c||(c=function(a){return a()});this.state="stopped";g=m=k;e=new re;d=k;this.ta=function(a){if(a!==this.state)this.state=a,this.N("state",a)};e.Db=$(function(){this.state!=="connecting"&&typeof console!=="undefined"&&console!==k&&console.warn("channelOpened in state "+this.state);this.ta("connected");g=m;return this.N("connected")},this);e.Bb=$(function(a,b){typeof console!=="undefined"&&console!==k&&console.error("channelError",d);d=we[b];return this.N("error",
d,b)},this);e.ib=$(function(a,b,c){a=b?b.concat(c):[];this.ta("waiting");this.N("disconnect",d,a);setTimeout(function(){i();return k},3E3);return this.reconnectTime=Date.now()},this);e.Cb=$(function(a,b){return this.N("message",b)},this);i=$(function(){this.state!=="waiting"&&typeof console!=="undefined"&&console!==k&&console.warn("reconnect from state "+this.state);this.ta("preparing");clearTimeout(l);this.N("preparing");m=new ae(b);m.i=e;d=k;return c($(function(){this.ta("connecting");this.N("connecting");
return m.Oa(""+a+"/test",""+a+"/bind",k,g!=k?g.Z:h,g!=k?g.Ba:h)},this))},this);l=k;this.connect=this.Oa=$(function(){this.state==="stopped"&&this.ta("waiting");return i()},this);this.disconnect=this.Hb=$(function(){clearTimeout(l);this.ta("stopped");return m.Hb()},this);this.send=this.send=function(a){return m.ub({JSON:Bc(a)})};this.sendMap=this.ub=function(a){return m.ub(a)};return this};se.tc();(typeof exports!=="undefined"&&exports!==k?exports:window).Channel=ve;